"""Agent State schema definition for the LangGraph execution pipeline."""

from typing import Optional, TypedDict


class AgentState(TypedDict):
    """Represents the shared conversational state across all graph nodes."""

    question: str
    """The raw user input question."""

    chat_history: Optional[list[dict]]
    """Sliding-window conversational message history (role & content dicts)."""

    standalone_question: Optional[str]
    """Contextualized query resolved of pronouns and previous conversation references."""

    revised_question: Optional[str]
    """Reformulated search query generated by the rewriter node during self-correction."""

    route: Optional[str]
    """Target routing classification: 'internal', 'web', 'chitchat', or 'unrelated'."""

    direct_response: Optional[str]
    """Direct textual response generated for chitchat or out-of-scope queries."""

    thought: Optional[str]
    """Chain-of-Thought (CoT) reasoning trace from the router node."""

    context: Optional[str]
    """Aggregated context string retrieved from FAISS chunks or Tavily search snippets."""

    sources: Optional[list[str]]
    """Ordered citations (page identifiers or web URLs) referenced in the context."""

    retry_count: int
    """Number of query reformulation attempts executed within the current turn."""

    is_sufficient: Optional[bool]
    """Assessment flag set by the grader node indicating context completeness."""

    k: Optional[int]
    """Dynamic chunk retrieval density chosen by the grader model (4 to 10)."""

    answer: Optional[str]
    """Final synthesized response text presented to the user."""